name: Build Debug APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure gradlew executable
        run: |
          if [ -f ./gradlew ]; then
            chmod +x ./gradlew || true
          fi

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Android commandline-tools (safe)
        env:
          ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
        run: |
          set -e
          mkdir -p "${ANDROID_SDK_ROOT}"
          TMPZIP="${ANDROID_SDK_ROOT}/cmdline.zip"
          if [ ! -f "$TMPZIP" ]; then
            curl -fsSL -o "$TMPZIP" "https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip"
          fi
          # extract safely
          TMPDIR="$(mktemp -d)"
          unzip -q -o "$TMPZIP" -d "$TMPDIR"
          mkdir -p "${ANDROID_SDK_ROOT}/cmdline-tools"
          # move children into cmdline-tools safely
          if [ -d "$TMPDIR/cmdline-tools" ]; then
            for ENTRY in "$TMPDIR/cmdline-tools"/*; do
              cp -a "$ENTRY" "${ANDROID_SDK_ROOT}/cmdline-tools/" || true
            done
          else
            cp -a "$TMPDIR"/* "${ANDROID_SDK_ROOT}/cmdline-tools/" || true
          fi
          rm -rf "$TMPDIR" || true

      - name: Accept licenses and install minimal SDK
        env:
          ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
        run: |
          export PATH="${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin:${ANDROID_SDK_ROOT}/cmdline-tools/bin:${PATH}"
          mkdir -p "${ANDROID_SDK_ROOT}/licenses"
          yes | sdkmanager --sdk_root="${ANDROID_SDK_ROOT}" "platform-tools" "platforms;android-33" "build-tools;33.0.2" || true
          yes | sdkmanager --sdk_root="${ANDROID_SDK_ROOT}" --licenses || true

      - name: Build (use wrapper)
        env:
          ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
        run: |
          if [ -x ./gradlew ]; then
            ./gradlew assembleDebug --no-daemon
          else
            echo "gradlew missing or not executable"
            exit 1
          fi

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apks
          path: app/build/outputs/apk/**/*.apk
          if-no-files-found: warn
