name: Build Debug APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Android SDK (platform-tools + cmdline-tools)
        uses: android-actions/setup-android@v2
        with:
          api-levels: '33,34'        # يمكنك تعديل حسب compileSdk الذي تستخدمه
          build-tools: '34.0.0'      # أو نسخة مناسبة للـ compileSdk
          ndk: ''                    # اترك فارغ إذا لا تحتاج NDK

      - name: Download Gradle 8.7
        run: |
          curl -sSLo gradle-8.7-bin.zip https://services.gradle.org/distributions/gradle-8.7-bin.zip
          unzip -q gradle-8.7-bin.zip -d $HOME
          echo "$HOME/gradle-8.7/bin" >> $GITHUB_PATH

      - name: Show versions (debug)
        run: |
          java -version
          gradle -v
          sdkmanager --version || true

      - name: Build Debug APK
        run: |
          # if project uses gradlew and it's present prefer it, else use system gradle
          if [ -f "./gradlew" ]; then
            chmod +x ./gradlew || true
            ./gradlew assembleDebug --no-daemon
          else
            gradle assembleDebug --no-daemon
          fi

      - name: Upload APK artifact (if exists)
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
