name: Generate Gradle Wrapper

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  gen-wrapper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Download Gradle 8.7
        run: |
          curl -sSLo gradle-8.7-bin.zip https://services.gradle.org/distributions/gradle-8.7-bin.zip
          unzip -q gradle-8.7-bin.zip -d $HOME
          echo "$HOME/gradle-8.7/bin" >> $GITHUB_PATH

      - name: Generate gradle wrapper (Gradle 8.7)
        run: |
          gradle wrapper --gradle-version 8.7 --distribution-type bin

      - name: Make gradlew executable
        run: chmod +x ./gradlew || true

      - name: Show created files (for debug)
        run: ls -la ./gradlew ./gradlew.bat ./gradle || true

      - name: Commit and push wrapper files (if changed)
        run: |
          git config user.email "actions@github.com"
          git config user.name "github-actions[bot]"
          git add ./gradlew ./gradlew.bat ./gradle/wrapper || true
          if ! git diff --staged --quiet; then
            git commit -m "chore: add gradle wrapper (generated by workflow)"
            git push origin HEAD:main
          else
            echo "No wrapper changes to commit"
          fi
