name: Generate Gradle Wrapper (Gradle 8.4)

# يتيح للـ workflow عمل commit و push لملفات في المستودع
permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  generate-wrapper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install wget & unzip
        run: sudo apt-get update -y && sudo apt-get install -y wget unzip

      - name: Remove any fake gradlew placeholders (if present)
        run: |
          set -e
          rm -f ./gradlew || true
          rm -f ./gradlew.bat || true
          # don't remove gradle/wrapper if it's real; we'll overwrite if needed
        shell: bash

      - name: Download Gradle distribution (8.4) and generate wrapper
        env:
          GRADLE_VERSION: 8.4
          TMPDIR: /tmp/gradle-dist
        run: |
          set -e
          echo "Using Gradle ${GRADLE_VERSION} to generate wrapper..."
          rm -rf "$TMPDIR"
          mkdir -p "$TMPDIR"
          wget -q "https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip" -O "$TMPDIR/gradle.zip"
          unzip -q "$TMPDIR/gradle.zip" -d "$TMPDIR"
          chmod +x "$TMPDIR"/gradle-*/bin/gradle
          # Run the wrapper task in the repository root to create gradlew + gradle/wrapper/*
          "$TMPDIR"/gradle-"${GRADLE_VERSION}"/bin/gradle wrapper --gradle-version "${GRADLE_VERSION}" --distribution-type bin --no-daemon || true
          echo "Listing generated wrapper files (if any):"
          ls -la || true
        shell: bash

      - name: Ensure gradlew is executable
        run: |
          if [ -f ./gradlew ]; then
            chmod +x ./gradlew
          fi

      - name: Show repository tree (for debug)
        run: |
          echo "=== repo tree (top) ==="
          ls -la
          echo "=== gradle wrapper dir ==="
          ls -la gradle || true
          ls -la gradle/wrapper || true

      - name: Commit wrapper files if added
        env:
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: actions@github.com
        run: |
          set -e
          git config user.name "${GIT_COMMITTER_NAME}"
          git config user.email "${GIT_COMMITTER_EMAIL}"
          # Stage typical wrapper files
          git add gradlew gradlew.bat gradle/wrapper || true
          # If there are staged changes, commit and push them to main
          if ! git diff --staged --quiet; then
            git commit -m "Add/Update Gradle wrapper (generated by workflow)"
            git push origin HEAD:main
            echo "Committed and pushed wrapper files."
          else
            echo "No wrapper changes to commit."
          fi
        shell: bash
