name: Generate Gradle Wrapper (Gradle 8.4)

on:
  workflow_dispatch:

jobs:
  generate-wrapper:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install unzip and wget
        run: sudo apt-get update && sudo apt-get install -y unzip wget

      - name: Download Gradle 8.4
        run: |
          wget https://services.gradle.org/distributions/gradle-8.4-bin.zip -O gradle-8.4-bin.zip
          unzip gradle-8.4-bin.zip -d gradle-dist

      - name: Create wrapper using downloaded Gradle
        run: |
          # use the downloaded gradle to run wrapper generation
          ./gradle-dist/gradle-8.4/bin/gradle wrapper --gradle-version 8.4 || true
        shell: bash

      - name: Show generated files
        run: ls -la

      - name: Commit wrapper files if added
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add gradlew gradlew.bat gradle/wrapper || true
          if ! git diff --staged --quiet; then
            git commit -m "Add gradle wrapper (generated by workflow)"
            git push origin HEAD:main
          else
            echo "No wrapper changes to commit."
          fi
