name: Generate Gradle Wrapper (Gradle 8.4)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-wrapper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install wget & unzip
        run: sudo apt-get update && sudo apt-get install -y wget unzip

      - name: Download Gradle distribution and generate wrapper
        run: |
          set -e
          GRADLE_VERSION=8.4
          TMPDIR=/tmp/gradle-dist
          mkdir -p $TMPDIR
          wget -q https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip -O $TMPDIR/gradle.zip
          unzip -q $TMPDIR/gradle.zip -d $TMPDIR
          # remove fake placeholder files so wrapper generation will create real ones
          rm -f ./gradlew ./gradlew.bat
          # use the downloaded gradle to run the wrapper task in your repo root
          $TMPDIR/gradle-${GRADLE_VERSION}/bin/gradle wrapper --gradle-version ${GRADLE_VERSION} --distribution-type bin --no-daemon || true
          ls -la gradlew gradlew.bat gradle/wrapper || true
        shell: bash

      - name: Commit wrapper files (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add gradlew gradlew.bat gradle/wrapper || true
          if ! git diff --staged --quiet; then
            git commit -m "Add Gradle wrapper (generated by workflow)"
            git push origin HEAD:main
          else
            echo "No wrapper changes to commit."
          fi
